module.exports = {
  A : require("./a"),
  H1 : require("./h1"),
  H2 : require("./h2"),
  H3 : require("./h3"),
  H4 : require("./h4"),
  H5 : require("./h5"),
  P : require("./p"),
  UL : require("./ul"),
  OL : require("./ol"),
  HR : require("./hr"),
  CODE : require("./code"),
  BOLD : require("./_bold"),
  ITALIC : require("./_italic"),
}
